
export const tesla_message = "My internship at Tesla was my first time living out of the MidWest, moving all the way to Palo Alto, CA.  I was a part of the Energy Products Software team.  I mostly worked on an internal web tool, created by my mentor, that the sales team used to sell more Powerwalls.  The first month or two I made updates/improvements to the web tool to get my feet wet.  Then I switched to making a web portal for customers to upload their load and/or solar data directly.  This saved the sales team several hours a week due to the high frequency of potential clients sending in bad data that they would have to fix.  This portal clearly informed the customer of any errors when they woule try and submit it and would require them to fix the errors before submission to the sales team.  The backend is run with ruby on rails and the frontend is created with React; neither of which I had any experience with before the internship. I learned a lot and had the time of my life during these 6 months.";

export const rc_message = "My internship at Rockwell Collins was my first taste of working in industry and thus taught me many valuable lessons.  I was originally hired to work on making the changes and improvements the clients wanted for the MH-53E but due to contract issues it never even got started during the 6 months that I was there.  For that reason I switched teams and worked on an automated testing framework for the CH-47 Chinook.  Throughout all of Rockwell when it was time to test the software, they would send a couple engineers to the labs and go through and manually click the bezels and check to see if the correct thing was displayed on the screen.  We fixed this issue by having it compare what was on the display to saved images of what was correct.  This involved two major steps: updating the test scripts to compare images instead of directing a user and capturing the images of what was correct. I knew this type of work isn't what I wanted to do full time, but I still learned a lot and am grateful for the opportunity.";

export const rose_message = "Rose Hulman is a small private engineering college in Terre Haute, IN.  It has been ranked #1 in undergraduate engineering for 18 years in a row.  I participated in a program called Fast Track Calculus which is a 5 week program in the summer where you take Calc 1, 2, and 3 and have it done before you even start your freshman year.  Spending every moment besides essentials of life doing calculus was super challenging.  Looking back it was one of the best decisions of my life as it helped me miss two quarters of school for co-ops and made me friendships that will last with me for the rest of my life.  It was also there that my friends conviced me to become a Computer Science major.  One of my favorite areas in CS has been web developement which is why I decided to make my website (this) from scratch.  Also the topic that has gotten me the most excited was actually a math class: Deep Learning.  I am glad to be rid of the homework and tests but miss my friends and the college atmosphere."

export const home_message = "My journey begins here.  Home.  My family and friends who have given me my character, morals, and beliefs are and always will be my home.  The place that has given me my rock solid foundation of faith in Jesus Christ is my home.  The people I know I can always fall back on if plans go awry is my home.  For 18 years, plus many transitions from the previous milestones you have read about, I have called Greenville, IL my home.  It is a small rural town 1 hour east of St. Louis.  It is where I became the man I am today.  I gained a strong work ethic by growing up/working on a dairy farm.  I developed a love of sports by playing and watching almost every single day.  I fostered a love for a plethora of different kinds of music whether it be country from the radio, hymns from church, today's hits from social activities, or rap from locker rooms.  My home still influences me to this day by my desire to live up to the standards set on me. This place/people will always have a special place in my heart."

export const epic_message = "Epic makes software for hospitals, doctor's offices, plus so many more health care facilities. Their campus is in Madison, WI and they have dedicated to making it a magical place. Whether it is their wizarding, storybook, farm, or any other campus, it is definitely a sight to see. I was on the team that made features for Social Care workers. I learned a lot about an industry I had no prior experience in. Also, their server code was in a programming language no one uses anymore (M) and the frontend was in .NET. Epic believed in getting the developers time shadowing their users to learn pain points first hand. The most significant of these trips was a 2 week trip to install our app for a hospital in Finland! That was only my second time ever out of the country. While my co-workers and the campus was great, I quickly learned the programming, business practices, and winters were not for me. So after a year of employment I began looking for other opportunities."

export const appfolio_message = "Appfolio makes a web tool for property managers to use to help them manage their properties. Appfolio believes AI is the next big technological gain to help push business forward. As such, I was on a team looking to drive the AI initiative: Smart Maintenance. The end goal was to have a bot text with tenants to discover/triage what is wrong and dispatch the right person to solve the maintenance problem. More specifically, my team worked on the rules that property managers would define to help our operators (eventually the bot) know how to handle a work order. For example for different issues they can set the urgency and which vendor to dispatch. I enjoyed working at Appfolio due to their culture and more modern development practices than my previous job (React, Ruby on Rails, CI/CD, hackdays, retros). Due to COVID, a lot of my time was working remotely back at home in Illinois, but the times I lived in Santa Barbara were a blast with both beaches and mountains. ";
